apiVersion: v1
kind: Service
metadata:
  name: {{ include "critiquely.fullname" . }}
  labels:
    {{- include "critiquely.labels" . | nindent 4 }}
spec:
  type: {{ .Values.receiver.service.type }}
  ports:
    - port: {{ .Values.receiver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "critiquely.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: receiver