[project]
name = "critiquely"
version = "1.0.0"
description = "Critiquely CLI"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
]

[project.scripts]
critiquely = "critiquely:critiquely.cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"