apiVersion: v2
name: critiquely
description: Automated code improvements for PRs
type: application
version: 0.1.7
appVersion: "1.0"

dependencies:
  - name: rabbitmq
    condition: rabbitmq.enabled
    version: "16.0.14"
    repository: "https://charts.bitnami.com/bitnami"
  - name: keda
    condition: keda.enabled
    version: 2.17.2
    repository: https://kedacore.github.io/charts